//! Generated by ggen from the admitted LifeGym world profile. Do not hand edit.
pub const DOMAINS: &[&str] = &[
"career",
"exam-preparation",
"finance",
"fitness",
"litigation",
"renovation",
"rental",
"shopping",
"team-building",
"travel",
];
pub const SERVICES: &[&str] = &[
"banking",
"brokerage",
"calendar",
"car",
"content_community",
"credit_card",
"delivery_logistics",
"ecommerce",
"email",
"flight",
"health_tracking",
"hotel",
"job_board",
"legal_search",
"listings",
"maps",
"notes",
"notification_hub",
"rail",
"reviews",
"visa_advisories",
"weather",
];
pub fn domain_count() -> usize { DOMAINS.len() }
pub fn service_count() -> usize { SERVICES.len() }
